Add missing cast from DyLibHandle (const void *) to HMODULE
This should fix the following compilation error on Windows:
error C2664: 'FreeLibrary' : cannot convert parameter 1 from 'cling::DynamicLibraryManager::DyLibHandle' to 'HMODULE'